# Generated by Django 5.0.1 on 2024-07-18 05:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='نام ارسال کننده پیام/نطر')),
                ('email', models.CharField(max_length=40, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=40, verbose_name='شماره تماس')),
                ('subject', models.CharField(max_length=40, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیغام')),
                ('show_in_comments', models.BooleanField(default=False, verbose_name='این پیام توسط مدیریت تایید شده و در بخش نمایش نطرات ویژه قابل نمایش است ')),
                ('show_in_comments_two', models.BooleanField(default=False, verbose_name='این پیام توسط مدیریت تایید شده و در بخش نمایش نطرات عادی قابل نمایش است ')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
            ],
            options={
                'verbose_name_plural': 'پیام ها',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='عنوان')),
                ('status', models.CharField(choices=[('1', 'منتشر شده'), ('0', 'پیش نویس')], max_length=7, verbose_name='وضعیت')),
                ('foodType', models.CharField(choices=[('2', 'شام'), ('1', 'ناهار'), ('0', 'صبحانه')], max_length=10, verbose_name='تایپ')),
                ('price', models.IntegerField(default=0, verbose_name='قیمت')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='food_image', verbose_name='عکس')),
            ],
            options={
                'verbose_name_plural': 'غذاها',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='عنوان')),
                ('discription', models.TextField(default=None, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('1', 'منتشر شده'), ('0', 'پیش نویس')], max_length=7, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name_plural': 'امکانات',
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(max_length=10, verbose_name='از تاریخ')),
                ('finish_date', models.CharField(max_length=10, verbose_name='تا تاریخ')),
                ('name', models.CharField(default='', max_length=20, verbose_name='نام')),
                ('family', models.CharField(default='', max_length=20, verbose_name='نام خانوادگی')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='شماره تلفن')),
                ('verify_code', models.CharField(blank=True, max_length=5, null=True)),
                ('city', models.CharField(blank=True, max_length=10, null=True, verbose_name='شهر')),
                ('address', models.CharField(blank=True, max_length=10, null=True, verbose_name='ادرس')),
                ('state', models.CharField(blank=True, max_length=10, null=True, verbose_name='استان')),
                ('email', models.CharField(blank=True, max_length=10, null=True, verbose_name='ایمیل')),
                ('total_price', models.IntegerField(default=0, verbose_name='مبلغ کل')),
            ],
            options={
                'verbose_name_plural': 'رزرو ها',
            },
        ),
        migrations.CreateModel(
            name='FoodReserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_food', models.CharField(blank=True, max_length=10, null=True, verbose_name='تعداد غذا')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.food', verbose_name='غذا سفارش داده شده')),
                ('reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.reserve', verbose_name='سفارش دهنده')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, verbose_name='قیمت')),
                ('name', models.CharField(max_length=50, verbose_name='نام اتاق')),
                ('number', models.IntegerField(default=0, verbose_name='شماره اتاق')),
                ('floor', models.IntegerField(default=0, verbose_name='طبقه اتاق')),
                ('suggested', models.BooleanField(default=False, verbose_name='این اتاق پیشنهاد شده است')),
                ('capacity', models.IntegerField(default=0, verbose_name='ظرفیت')),
                ('image', models.ImageField(upload_to='room_image', verbose_name='عکس')),
                ('description', models.TextField(blank=True, default='')),
                ('option', models.ManyToManyField(to='app.option', verbose_name='امکانات')),
            ],
            options={
                'verbose_name_plural': 'اتاق ها',
            },
        ),
        migrations.AddField(
            model_name='reserve',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.room', verbose_name='اتاق'),
        ),
    ]
